# Generated by Django 4.2.20 on 2025-05-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion_masinfo', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Landing Page Configuración',
                'verbose_name_plural': 'Landing Page Configuraciones',
            },
        ),
    ]
