# Generated by Django 4.2 on 2023-05-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='mailescuela',
            name='cue',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cue',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='telefonoescuela',
            name='cue',
        ),
        migrations.DeleteModel(
            name='Escuela',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
        migrations.DeleteModel(
            name='MailEscuela',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='PartidoPBA',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.DeleteModel(
            name='TelefonoEscuela',
        ),
    ]
