# Generated by Django 4.2 on 2023-05-16 16:59

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_localidad_partido_remove_localidad_provincia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to=apps.core.models._generar_ruta_documento)),
            ],
        ),
    ]
