# Generated by Django 4.2 on 2023-05-16 18:24

import apps.inscripcion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='denominacion', max_length=20)),
                ('capacidad', models.IntegerField(db_column='capacidad')),
                ('aire', models.BooleanField(db_column='aire')),
                ('proyector', models.BooleanField(db_column='proyector')),
                ('accesibilidad', models.BooleanField(db_column='accesibiliad')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aula',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('detalle', models.CharField(db_column='detalle', max_length=45)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=4)),
                ('ingreso_anio', models.IntegerField(db_column='ingresoanio')),
                ('aula', models.ForeignKey(db_column='aula', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.aula')),
            ],
            options={
                'verbose_name': 'Comision',
                'verbose_name_plural': 'Comisiones',
                'db_table': 'comision',
                'ordering': ['ingreso_anio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbu', models.IntegerField(db_column='cbu')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
                'ordering': ['persona'],
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('cue', models.CharField(db_column='CUE', max_length=9, primary_key=True, serialize=False)),
                ('gestion', models.CharField(choices=[('privada', 'Privada'), ('publica', 'Publica'), ('mixta', 'Mixta'), ('social/cooperativa', 'Social/Cooperativa')], db_column='gestion', max_length=20)),
                ('ambito', models.CharField(choices=[('rural', 'Rural'), ('urbano', 'Urbano')], db_column='ambito', max_length=20)),
                ('tecnica', models.BooleanField(db_column='tecnica')),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('domicilio_calle', models.CharField(db_column='domiciliocalle', max_length=150)),
                ('domicilio_altura', models.IntegerField(db_column='domicilioaltura')),
                ('domicilio_cpa', models.CharField(db_column='domicilioCPA', max_length=8)),
                ('domicilio_cp4', models.CharField(db_column='domicilioCP4', max_length=4)),
                ('domicilio_coordenada_x', models.FloatField(db_column='domiciliocoordenadaX', default=0)),
                ('domicilio_coordenada_y', models.FloatField(db_column='domiciliocoordenadaY', default=0)),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'db_table': 'escuela',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('credencial', models.IntegerField(db_column='credencial', primary_key=True, serialize=False)),
                ('legajo', models.IntegerField(db_column='legajo', default=0)),
                ('cuil', models.CharField(blank=True, db_column='cuil', max_length=13, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino')], db_column='sexo', max_length=1, null=True)),
                ('nombre_autopercibido', models.CharField(blank=True, db_column='nombreautopercibido', max_length=60, null=True)),
                ('anio_egreso', models.IntegerField(blank=True, db_column='escuelaanioegreso', null=True)),
                ('emergencia_telefono', models.CharField(blank=True, db_column='emergenciatelefono', max_length=20, null=True)),
                ('emergencia_contacto', models.CharField(blank=True, db_column='emergenciacontacto', max_length=60, null=True)),
                ('especialidad', models.IntegerField(blank=True, choices=[(5, 'Ing. en Sistemas de Informacion'), (7, 'Ing. en Energia Electrica'), (17, 'Ing. Mecanica'), (24, 'Ing. Industrial'), (27, 'Ing. Quimica'), (31, 'Ing. Civil')], db_column='especialidad', null=True)),
                ('turno', models.CharField(blank=True, choices=[('m', 'Turno Mañana'), ('t', 'Turno Tarde'), ('n', 'Turno Noche')], db_column='turno', max_length=1, null=True)),
                ('modalidad', models.IntegerField(blank=True, db_column='modalidad', null=True)),
                ('escuela', models.ForeignKey(blank=True, db_column='escuela', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.escuela')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantess',
                'db_table': 'estudiante',
                'ordering': ['credencial'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'db_table': 'genero',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=51)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadCursado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=15)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=150)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'db_table': 'modalidadcursada',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('coord_x', models.FloatField(db_column='coordenadaX')),
                ('coord_y', models.FloatField(db_column='coordenadaY')),
                ('nacionalidad', models.CharField(db_column='nacionalidad', max_length=100)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PartidoPBA',
            fields=[
                ('id', models.CharField(db_column='id', max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'db_table': 'partidopba',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_column='tipo', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'tipodocumento',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='TituloSecundario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='titulo', max_length=45)),
                ('tecnico', models.BooleanField(db_column='tecnico')),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
                'db_table': 'tituloescuela',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('detalle', models.CharField(db_column='detalle', max_length=100)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
            },
        ),
        migrations.CreateModel(
            name='TelefonoEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_column='telefono', max_length=50)),
                ('escuela', models.ForeignKey(db_column='escuela', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.escuela')),
            ],
            options={
                'verbose_name': 'Telefono de la Escuela',
                'verbose_name_plural': 'Telefonos de las Escuelas',
                'db_table': 'telefonoEscuela',
                'ordering': ['escuela'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('pais', models.ForeignKey(db_column='pais', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(db_column='apellidos', max_length=60)),
                ('nombres', models.CharField(db_column='nombres', max_length=60)),
                ('fecha_nacimiento', models.DateField(db_column='nacimientofecha')),
                ('numero_documento', models.CharField(db_column='documentonumero', max_length=16)),
                ('domicilio_piso', models.CharField(blank=True, db_column='domiciliopiso', default=None, max_length=4, null=True)),
                ('domicilio_departamento', models.CharField(blank=True, db_column='domiciliodepartamento', default=None, max_length=4, null=True)),
                ('domicilio_barrio', models.CharField(blank=True, db_column='domiciliobarrio', default=None, max_length=30, null=True)),
                ('domicilio_cpa', models.CharField(db_column='domicilioCPA', max_length=8)),
                ('domicilio_cp4', models.CharField(db_column='domicilioCP4', max_length=4)),
                ('domicilio_coordenada_x', models.FloatField(db_column='domiciliocoordenadaX')),
                ('domicilio_coordenada_y', models.FloatField(db_column='domiciliocoordenadaY')),
                ('telefono', models.CharField(db_column='telefono', max_length=20)),
                ('correo', models.EmailField(db_column='email', max_length=254)),
                ('documento_tipo', models.ForeignKey(db_column='documentotipo', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.tipodocumento')),
                ('domicilio_localidad', models.ForeignKey(db_column='domiciliolocalidad', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.localidad')),
                ('nacionalidad', models.ForeignKey(db_column='nacionalidad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais_nacionalidad', to='inscripcion.pais')),
                ('pais_documento', models.ForeignKey(db_column='documentopaisemisor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_pais_emisor', to='inscripcion.pais')),
                ('pais_nacimiento', models.ForeignKey(db_column='nacimientopais', on_delete=django.db.models.deletion.DO_NOTHING, related_name='nacimiento_pais', to='inscripcion.pais')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(db_column='nota')),
                ('comision', models.ForeignKey(db_column='comision', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.comision')),
                ('estudiante', models.ForeignKey(db_column='estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.estudiante')),
                ('unidad', models.ForeignKey(db_column='unidad', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.unidad')),
            ],
            options={
                'verbose_name': 'Parcial',
                'verbose_name_plural': 'Parciales',
                'db_table': 'parcial',
            },
        ),
        migrations.CreateModel(
            name='MailEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(db_column='mail', max_length=254)),
                ('escuela', models.ForeignKey(db_column='escuela', max_length=9, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.escuela')),
            ],
            options={
                'verbose_name': 'Correo Electronico de la Escuela',
                'verbose_name_plural': 'Correos Electronicos de las Escuelas',
                'db_table': 'mailescuela',
                'ordering': ['escuela'],
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='partido',
            field=models.ForeignKey(blank=True, db_column='Partido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.partidopba'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(db_column='provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.provincia'),
        ),
        migrations.CreateModel(
            name='EvaluacionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(db_column='aprobado')),
                ('comision', models.ForeignKey(db_column='comision', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.comision')),
                ('estudiante', models.ForeignKey(db_column='estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.estudiante')),
                ('unidad', models.ForeignKey(db_column='unidad', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.unidad')),
            ],
            options={
                'verbose_name': 'Evaluacion de Unidad',
                'verbose_name_plural': 'Evaluaciones de Unidades',
                'db_table': 'evaluacionunidad',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(db_column='orden')),
                ('aprobado', models.BooleanField(db_column='aprobado')),
                ('estudiante', models.ForeignKey(db_column='estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.estudiante')),
                ('parcial', models.ForeignKey(db_column='parcial', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.parcial')),
            ],
            options={
                'verbose_name': 'Evaluacion Diaria',
                'verbose_name_plural': 'Evaluaciones Diarias',
                'db_table': 'evaluacionesdiarias',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.ForeignKey(blank=True, db_column='genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.genero'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.ForeignKey(db_column='persona', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.persona'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='titulo_secundario',
            field=models.ForeignKey(blank=True, db_column='tituloescuela', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.titulosecundario'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='domicilio_localidad',
            field=models.ForeignKey(db_column='domiciliolocalidad', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.localidad'),
        ),
        migrations.CreateModel(
            name='EquipoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.BooleanField(db_column='profesor')),
                ('comision', models.ForeignKey(db_column='comision', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.comision')),
                ('docente', models.ForeignKey(db_column='docente', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.docente')),
            ],
            options={
                'verbose_name': 'Equipo Docente',
                'verbose_name_plural': 'Equipos Docentes',
                'db_table': 'equipodocente',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='genero',
            field=models.ForeignKey(db_column='genero', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.genero'),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(db_column='persona', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.persona'),
        ),
        migrations.AddField(
            model_name='comision',
            name='estudiante',
            field=models.ManyToManyField(to='inscripcion.estudiante'),
        ),
        migrations.AddField(
            model_name='comision',
            name='modalidad',
            field=models.ForeignKey(db_column='modalidadcursada', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.modalidadcursado'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_column='fechahora')),
                ('clase', models.ForeignKey(db_column='clase_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.clase')),
                ('comision', models.ForeignKey(db_column='comision_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.comision')),
                ('estudiante', models.ForeignKey(db_column='estudiante_credencial', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(db_column='tipo')),
                ('path', models.FileField(db_column='ubicacion', upload_to=apps.inscripcion.models._generar_ruta_documento)),
                ('persona', models.ForeignKey(db_column='persona', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.persona')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivoss',
                'db_table': 'imagenes',
            },
        ),
        migrations.AddConstraint(
            model_name='equipodocente',
            constraint=models.UniqueConstraint(fields=('comision', 'docente'), name='unique_combination_comision_docente'),
        ),
    ]
