# Generated by Django 4.2 on 2023-05-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evaluaciondiaria',
            table='evaluaciondiaria',
        ),
    ]
