# Generated by Django 4.2.1 on 2023-05-21 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_alter_evaluaciondiaria_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(db_column='denominacion', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='estudiante',
            field=models.ManyToManyField(db_table='matricula', to='inscripcion.estudiante'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cbu',
            field=models.IntegerField(db_column='cbu', unique=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='cue',
            field=models.CharField(db_column='CUE', max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='credencial',
            field=models.IntegerField(auto_created=True, db_column='credencial', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='legajo',
            field=models.IntegerField(db_column='legajo', default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='persona',
            field=models.OneToOneField(db_column='persona', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.persona'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='modalidadcursado',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nacionalidad',
            field=models.CharField(db_column='nacionalidad', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='partidopba',
            name='id',
            field=models.CharField(db_column='id', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='partidopba',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(db_column='email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(db_column='documentonumero', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais_documento',
            field=models.ForeignKey(db_column='documentopaisemisor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais_documento_emisor', to='inscripcion.pais'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais_nacimiento',
            field=models.ForeignKey(db_column='nacimientopais', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais_nacimiento', to='inscripcion.pais'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='tipo',
            field=models.CharField(db_column='tipo', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='titulosecundario',
            name='titulo',
            field=models.CharField(db_column='titulo', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=45, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('clase', 'estudiante', 'comision')},
        ),
        migrations.AlterUniqueTogether(
            name='comision',
            unique_together={('nombre', 'ingreso_anio')},
        ),
    ]
