# Generated by Django 4.2.1 on 2023-06-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_alter_aula_nombre_alter_clase_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='domicilio_calle',
            field=models.CharField(blank=True, db_column='domiciliocalle', default=None, max_length=100, null=True),
        ),
    ]
