# Generated by Django 4.2.1 on 2023-06-05 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_persona_domicilio_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='pais_documento',
            field=models.ForeignKey(blank=True, db_column='documentopaisemisor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais_documento_emisor', to='inscripcion.pais'),
        ),
    ]
