# Generated by Django 4.2.1 on 2023-06-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_alter_persona_pais_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio_localidad',
            field=models.ForeignKey(blank=True, db_column='domiciliolocalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.localidad'),
        ),
    ]
