# Generated by Django 4.2.1 on 2023-06-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0006_alter_persona_domicilio_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio_coordenada_x',
            field=models.FloatField(blank=True, db_column='domiciliocoordenadaX', null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domicilio_coordenada_y',
            field=models.FloatField(blank=True, db_column='domiciliocoordenadaY', null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domicilio_cp4',
            field=models.CharField(blank=True, db_column='domicilioCP4', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domicilio_cpa',
            field=models.CharField(blank=True, db_column='domicilioCPA', max_length=8, null=True),
        ),
    ]
