# Generated by Django 4.2.1 on 2023-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0007_alter_persona_domicilio_coordenada_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='credencial',
            field=models.AutoField(db_column='credencial', primary_key=True, serialize=False),
        ),
    ]
