# Generated by Django 4.2.1 on 2023-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0008_alter_estudiante_credencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='legajo',
            field=models.IntegerField(db_column='legajo', default=0),
        ),
    ]
