# Generated by Django 4.2.2 on 2023-06-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0009_alter_estudiante_legajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('file_documento', models.FileField(upload_to='')),
                ('file_certificado', models.FileField(upload_to='')),
                ('modalidad', models.CharField(choices=[('p', 'Presencial'), ('s', 'Semi-Presencial'), ('v', 'Virtual')], max_length=50)),
                ('periodo', models.CharField(choices=[('e', 'Extensivo - Agosto-Diciembre'), ('i', 'Intensivo - Febrero-Marzo')], max_length=50)),
            ],
            options={
                'verbose_name': 'Documentacion',
                'verbose_name_plural': 'Documentaciones',
            },
        ),
    ]
