# Generated by Django 4.2.2 on 2023-07-01 18:10

import apps.inscripcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0010_documentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='turno',
            field=models.CharField(choices=[('m', 'Turno Mañana'), ('t', 'Turno Tarde')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='file_certificado',
            field=models.FileField(upload_to=apps.inscripcion.models._generar_ruta_documento),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='file_documento',
            field=models.FileField(upload_to=apps.inscripcion.models._generar_ruta_documento),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='modalidad',
            field=models.CharField(choices=[('p', 'Presencial'), ('s', 'Semi-Presencial'), ('l', 'Libre')], max_length=1),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='periodo',
            field=models.CharField(choices=[('e', 'Extensivo - Agosto-Diciembre'), ('i', 'Intensivo - Febrero-Marzo')], max_length=1),
        ),
    ]
