# Generated by Django 4.2.2 on 2023-07-01 18:14

import apps.inscripcion.models
import apps.inscripcion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0011_documentacion_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='file_certificado',
            field=models.FileField(upload_to=apps.inscripcion.models._generar_ruta_documento, validators=[apps.inscripcion.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='file_documento',
            field=models.FileField(upload_to=apps.inscripcion.models._generar_ruta_documento, validators=[apps.inscripcion.validators.validate_file_extension]),
        ),
    ]
