# Generated by Django 4.2.2 on 2023-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0012_alter_documentacion_file_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
