# Generated by Django 4.2.2 on 2023-07-04 03:54

import apps.inscripcion.models
import apps.inscripcion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0013_documentacion_aprobada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='file_certificado',
            field=models.FileField(upload_to=apps.inscripcion.models._generar_ruta_file_certificado, validators=[apps.inscripcion.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='file_documento',
            field=models.FileField(upload_to=apps.inscripcion.models._generar_ruta_file_documento, validators=[apps.inscripcion.validators.validate_file_extension]),
        ),
    ]
