# Generated by Django 4.2.2 on 2023-07-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0014_alter_documentacion_file_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='num_documento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
