# Generated by Django 4.2.3 on 2023-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0015_alter_documentacion_correo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['credencial'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='periodo',
            field=models.CharField(choices=[('i', 'Intensivo - Febrero-Marzo')], max_length=1),
        ),
    ]
