# Generated by Django 4.2.3 on 2023-09-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0016_alter_estudiante_options_alter_documentacion_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidopba',
            name='provincia',
            field=models.ForeignKey(db_column='provincia', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.provincia'),
            preserve_default=False,
        ),
    ]
