# Generated by Django 4.2.3 on 2023-09-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0017_partidopba_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='domicilio_altura',
            field=models.CharField(blank=True, db_column='domicilioaltura', default=None, max_length=10, null=True),
        ),
    ]
