# Generated by Django 4.2.3 on 2023-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0018_persona_domicilio_altura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='cuil',
        ),
        migrations.AddField(
            model_name='persona',
            name='cuil',
            field=models.CharField(blank=True, db_column='cuil', max_length=13, null=True),
        ),
    ]
