# Generated by Django 4.2.3 on 2023-09-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0019_remove_estudiante_cuil_persona_cuil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'db_table': 'generos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre_autopercibido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='sexo',
        ),
        migrations.AddField(
            model_name='persona',
            name='genero_otro',
            field=models.CharField(db_column='genero_otro', default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre_autopercibido',
            field=models.CharField(blank=True, db_column='nombreautopercibido', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino')], db_column='sexo', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(blank=True, db_column='genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.generos'),
        ),
    ]
