# Generated by Django 4.2.3 on 2023-09-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0020_generos_remove_estudiante_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
    ]
