# Generated by Django 4.2.3 on 2023-09-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0021_remove_docente_genero_remove_persona_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(blank=True, db_column='genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.genero'),
        ),
    ]
