# Generated by Django 4.2.3 on 2023-09-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0022_persona_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='domicilio_pais',
            field=models.ForeignKey(blank=True, db_column='domiciliopais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais_domicilio', to='inscripcion.pais'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='modalidad',
            field=models.CharField(choices=[('p', 'Presencial'), ('s', 'Semi-Presencial'), ('l', 'Libre')], db_column='modalidad', max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino'), ('n', 'No Binario')], db_column='sexo', max_length=1, null=True),
        ),
    ]
