# Generated by Django 4.2.3 on 2023-10-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0023_persona_domicilio_pais_alter_estudiante_modalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='anio_egreso',
            field=models.IntegerField(db_column='escuelaanioegreso', default=1900),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='emergencia_contacto',
            field=models.CharField(db_column='emergenciacontacto', default=123, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='emergencia_telefono',
            field=models.CharField(db_column='emergenciatelefono', default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='escuela',
            field=models.ForeignKey(db_column='escuela', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='especialidad',
            field=models.IntegerField(choices=[(5, 'Ing. en Sistemas de Informacion'), (7, 'Ing. en Energia Electrica'), (17, 'Ing. Mecanica'), (24, 'Ing. Industrial'), (27, 'Ing. Quimica'), (31, 'Ing. Civil')], db_column='especialidad', default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='titulo_secundario',
            field=models.CharField(db_column='tituloescuela', default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='turno',
            field=models.CharField(choices=[('m', 'Turno Mañana'), ('t', 'Turno Tarde'), ('n', 'Turno Noche')], db_column='turno', default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='domicilio_pais',
            field=models.ForeignKey(db_column='domiciliopais', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais_domicilio', to='inscripcion.pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(db_column='genero', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.genero'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero_otro',
            field=models.CharField(blank=True, db_column='genero_otro', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais_documento',
            field=models.ForeignKey(db_column='documentopaisemisor', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais_documento_emisor', to='inscripcion.pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('n', 'No Binario')], db_column='sexo', default=1, max_length=1),
            preserve_default=False,
        ),
    ]
