# Generated by Django 4.2.3 on 2023-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0024_alter_estudiante_anio_egreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='tipo',
            field=models.CharField(db_column='tipo', max_length=20),
        ),
    ]
