# Generated by Django 4.2.3 on 2023-10-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0025_alter_archivos_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivos',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AddField(
            model_name='archivos',
            name='estado',
            field=models.IntegerField(db_column='estado', default=0),
        ),
    ]
