# Generated by Django 4.2.3 on 2023-10-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0026_alter_archivos_options_archivos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='ambito',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urbano', 'Urbano')], db_column='ambito', max_length=20),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='domicilio_calle',
            field=models.CharField(db_column='domiciliocalle', max_length=200),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='gestion',
            field=models.CharField(choices=[('Privado', 'Privado'), ('Estatal', 'Estatal'), ('Social/cooperativa', 'Social/cooperativa')], db_column='gestion', max_length=20),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=200),
        ),
    ]
