# Generated by Django 4.2.3 on 2023-10-17 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0027_alter_escuela_ambito_alter_escuela_domicilio_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='escuela',
            field=models.ForeignKey(blank=True, db_column='escuela', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.escuela'),
        ),
    ]
