# Generated by Django 4.2.3 on 2023-10-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0028_alter_estudiante_escuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='ambito',
            field=models.CharField(choices=[('rural', 'Rural'), ('urbano', 'Urbano'), ('rural agrupado', 'Rural Agrupado'), ('Rural disperso', 'Rural Disperso')], db_column='ambito', max_length=20),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='gestion',
            field=models.CharField(choices=[('privado', 'Privado'), ('estatal', 'Estatal'), ('social/cooperativa', 'Social/Cooperativa')], db_column='gestion', max_length=20),
        ),
    ]
