# Generated by Django 4.2.3 on 2023-11-20 18:43

import apps.inscripcion.models
import apps.inscripcion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0029_alter_escuela_ambito_alter_escuela_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='path',
            field=models.FileField(db_column='ubicacion', upload_to=apps.inscripcion.models._generar_ruta_documento, validators=[apps.inscripcion.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nacionalidad',
            field=models.CharField(db_column='nacionalidad', max_length=100),
        ),
    ]
