# Generated by Django 4.2.16 on 2024-11-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0030_alter_archivos_path_alter_pais_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('inscripcion_inicio', models.DateField()),
                ('inscripcion_cierre', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('periodo_inicio', models.CharField(choices=[('01_2024', 'Enero 2024'), ('02_2024', 'Febrero 2024'), ('03_2024', 'Marzo 2024'), ('04_2024', 'Abril 2024'), ('05_2024', 'Mayo 2024'), ('06_2024', 'Junio 2024'), ('07_2024', 'Julio 2024'), ('08_2024', 'Agosto 2024'), ('09_2024', 'Septiembre 2024'), ('10_2024', 'Octubre 2024'), ('11_2024', 'Noviembre 2024'), ('12_2024', 'Diciembre 2024'), ('01_2025', 'Enero 2025'), ('02_2025', 'Febrero 2025'), ('03_2025', 'Marzo 2025'), ('04_2025', 'Abril 2025'), ('05_2025', 'Mayo 2025'), ('06_2025', 'Junio 2025'), ('07_2025', 'Julio 2025'), ('08_2025', 'Agosto 2025'), ('09_2025', 'Septiembre 2025'), ('10_2025', 'Octubre 2025'), ('11_2025', 'Noviembre 2025'), ('12_2025', 'Diciembre 2025')], max_length=7)),
                ('periodo_cierre', models.CharField(choices=[('01_2024', 'Enero 2024'), ('02_2024', 'Febrero 2024'), ('03_2024', 'Marzo 2024'), ('04_2024', 'Abril 2024'), ('05_2024', 'Mayo 2024'), ('06_2024', 'Junio 2024'), ('07_2024', 'Julio 2024'), ('08_2024', 'Agosto 2024'), ('09_2024', 'Septiembre 2024'), ('10_2024', 'Octubre 2024'), ('11_2024', 'Noviembre 2024'), ('12_2024', 'Diciembre 2024'), ('01_2025', 'Enero 2025'), ('02_2025', 'Febrero 2025'), ('03_2025', 'Marzo 2025'), ('04_2025', 'Abril 2025'), ('05_2025', 'Mayo 2025'), ('06_2025', 'Junio 2025'), ('07_2025', 'Julio 2025'), ('08_2025', 'Agosto 2025'), ('09_2025', 'Septiembre 2025'), ('10_2025', 'Octubre 2025'), ('11_2025', 'Noviembre 2025'), ('12_2025', 'Diciembre 2025')], max_length=7)),
                ('modalidad', models.ManyToManyField(to='inscripcion.modalidadcursado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('libre', 'Libre'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], max_length=11)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='inscripcion.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='inscripcion.estudiante')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidad', to='inscripcion.modalidadcursado')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
