# Generated by Django 4.2.16 on 2024-11-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0030_alter_archivos_path_alter_pais_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('inscripcion_inicio', models.DateField()),
                ('inscripcion_cierre', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('periodo_inicio', models.CharField(choices=[('01_2024', 'January 2024'), ('02_2024', 'February 2024'), ('03_2024', 'March 2024'), ('04_2024', 'April 2024'), ('05_2024', 'May 2024'), ('06_2024', 'June 2024'), ('07_2024', 'July 2024'), ('08_2024', 'August 2024'), ('09_2024', 'September 2024'), ('10_2024', 'October 2024'), ('11_2024', 'November 2024'), ('12_2024', 'December 2024')], max_length=7)),
                ('periodo_cierre', models.CharField(choices=[('01_2024', 'January 2024'), ('02_2024', 'February 2024'), ('03_2024', 'March 2024'), ('04_2024', 'April 2024'), ('05_2024', 'May 2024'), ('06_2024', 'June 2024'), ('07_2024', 'July 2024'), ('08_2024', 'August 2024'), ('09_2024', 'September 2024'), ('10_2024', 'October 2024'), ('11_2024', 'November 2024'), ('12_2024', 'December 2024')], max_length=7)),
                ('modalidad', models.ManyToManyField(to='inscripcion.modalidadcursado')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('libre', 'Libre'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], max_length=11)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='inscripcion.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='inscripcion.estudiante')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidad', to='inscripcion.modalidadcursado')),
            ],
        ),
    ]
