# Generated by Django 4.2.16 on 2024-11-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0031_curso_inscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripcion', 'verbose_name_plural': 'Inscripciones'},
        ),
    ]
