# Generated by Django 4.2.16 on 2024-11-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0032_inscripcion_especialidad_inscripcion_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='periodo_cierre',
            field=models.CharField(choices=[('Enero-2024', 'Enero-2024'), ('Febrero-2024', 'Febrero-2024'), ('Marzo-2024', 'Marzo-2024'), ('Abril-2024', 'Abril-2024'), ('Mayo-2024', 'Mayo-2024'), ('Junio-2024', 'Junio-2024'), ('Julio-2024', 'Julio-2024'), ('Agosto-2024', 'Agosto-2024'), ('Septiembre-2024', 'Septiembre-2024'), ('Octubre-2024', 'Octubre-2024'), ('Noviembre-2024', 'Noviembre-2024'), ('Diciembre-2024', 'Diciembre-2024'), ('Enero-2025', 'Enero-2025'), ('Febrero-2025', 'Febrero-2025'), ('Marzo-2025', 'Marzo-2025'), ('Abril-2025', 'Abril-2025'), ('Mayo-2025', 'Mayo-2025'), ('Junio-2025', 'Junio-2025'), ('Julio-2025', 'Julio-2025'), ('Agosto-2025', 'Agosto-2025'), ('Septiembre-2025', 'Septiembre-2025'), ('Octubre-2025', 'Octubre-2025'), ('Noviembre-2025', 'Noviembre-2025'), ('Diciembre-2025', 'Diciembre-2025')], max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='periodo_inicio',
            field=models.CharField(choices=[('Enero-2024', 'Enero-2024'), ('Febrero-2024', 'Febrero-2024'), ('Marzo-2024', 'Marzo-2024'), ('Abril-2024', 'Abril-2024'), ('Mayo-2024', 'Mayo-2024'), ('Junio-2024', 'Junio-2024'), ('Julio-2024', 'Julio-2024'), ('Agosto-2024', 'Agosto-2024'), ('Septiembre-2024', 'Septiembre-2024'), ('Octubre-2024', 'Octubre-2024'), ('Noviembre-2024', 'Noviembre-2024'), ('Diciembre-2024', 'Diciembre-2024'), ('Enero-2025', 'Enero-2025'), ('Febrero-2025', 'Febrero-2025'), ('Marzo-2025', 'Marzo-2025'), ('Abril-2025', 'Abril-2025'), ('Mayo-2025', 'Mayo-2025'), ('Junio-2025', 'Junio-2025'), ('Julio-2025', 'Julio-2025'), ('Agosto-2025', 'Agosto-2025'), ('Septiembre-2025', 'Septiembre-2025'), ('Octubre-2025', 'Octubre-2025'), ('Noviembre-2025', 'Noviembre-2025'), ('Diciembre-2025', 'Diciembre-2025')], max_length=15),
        ),
    ]
