# Generated by Django 4.2.16 on 2024-11-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0036_alter_inscripcion_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('turno', models.ManyToManyField(to='inscripcion.turno')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='especialidad',
            field=models.ForeignKey(default='l', on_delete=django.db.models.deletion.CASCADE, related_name='especialidad', to='inscripcion.especialidad'),
        ),
    ]
