# Generated by Django 4.2.16 on 2024-11-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0037_especialidad_alter_inscripcion_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidad', to='inscripcion.especialidad'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidad', to='inscripcion.modalidadcursado'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='inscripcion.turno'),
        ),
    ]
