# Generated by Django 4.2.20 on 2025-05-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0038_alter_especialidad_id_alter_inscripcion_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='periodo_cierre',
            field=models.CharField(choices=[('Enero-2025', 'Enero-2025'), ('Febrero-2025', 'Febrero-2025'), ('Marzo-2025', 'Marzo-2025'), ('Abril-2025', 'Abril-2025'), ('Mayo-2025', 'Mayo-2025'), ('Junio-2025', 'Junio-2025'), ('Julio-2025', 'Julio-2025'), ('Agosto-2025', 'Agosto-2025'), ('Septiembre-2025', 'Septiembre-2025'), ('Octubre-2025', 'Octubre-2025'), ('Noviembre-2025', 'Noviembre-2025'), ('Diciembre-2025', 'Diciembre-2025'), ('Enero-2026', 'Enero-2026'), ('Febrero-2026', 'Febrero-2026'), ('Marzo-2026', 'Marzo-2026'), ('Abril-2026', 'Abril-2026'), ('Mayo-2026', 'Mayo-2026'), ('Junio-2026', 'Junio-2026'), ('Julio-2026', 'Julio-2026'), ('Agosto-2026', 'Agosto-2026'), ('Septiembre-2026', 'Septiembre-2026'), ('Octubre-2026', 'Octubre-2026'), ('Noviembre-2026', 'Noviembre-2026'), ('Diciembre-2026', 'Diciembre-2026')], max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='periodo_inicio',
            field=models.CharField(choices=[('Enero-2025', 'Enero-2025'), ('Febrero-2025', 'Febrero-2025'), ('Marzo-2025', 'Marzo-2025'), ('Abril-2025', 'Abril-2025'), ('Mayo-2025', 'Mayo-2025'), ('Junio-2025', 'Junio-2025'), ('Julio-2025', 'Julio-2025'), ('Agosto-2025', 'Agosto-2025'), ('Septiembre-2025', 'Septiembre-2025'), ('Octubre-2025', 'Octubre-2025'), ('Noviembre-2025', 'Noviembre-2025'), ('Diciembre-2025', 'Diciembre-2025'), ('Enero-2026', 'Enero-2026'), ('Febrero-2026', 'Febrero-2026'), ('Marzo-2026', 'Marzo-2026'), ('Abril-2026', 'Abril-2026'), ('Mayo-2026', 'Mayo-2026'), ('Junio-2026', 'Junio-2026'), ('Julio-2026', 'Julio-2026'), ('Agosto-2026', 'Agosto-2026'), ('Septiembre-2026', 'Septiembre-2026'), ('Octubre-2026', 'Octubre-2026'), ('Noviembre-2026', 'Noviembre-2026'), ('Diciembre-2026', 'Diciembre-2026')], max_length=15),
        ),
    ]
