# Generated by Django 4.2 on 2023-05-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('cue', models.CharField(db_column='CUE_escuela', max_length=12, primary_key=True, serialize=False)),
                ('gestion', models.CharField(choices=[('privada', 'Privada'), ('publica', 'Publica'), ('mixta', 'Mixta'), ('social/cooperativa', 'Social/Cooperativa')], db_column='gestion_escuela', max_length=19)),
                ('ambito', models.CharField(choices=[('rural', 'Rural'), ('urbano', 'Urbano')], db_column='ambito_escuela', max_length=7)),
                ('tecnica', models.BooleanField(db_column='tecnica_escuela')),
                ('nombre', models.CharField(db_column='nombre_escuela', max_length=150)),
                ('domicilio', models.CharField(db_column='domicilio_escuela', max_length=180)),
                ('coordenada_1', models.FloatField(db_column='coordenada1_escuela', default=0)),
                ('coordenada_2', models.FloatField(db_column='coordenada2_escuela', default=0)),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'db_table': 'escuela',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.IntegerField(db_column='id_localidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_localidad', max_length=51)),
                ('coord_1', models.FloatField(db_column='coordenada1_localidad')),
                ('coord_2', models.FloatField(db_column='coordenada2_localidad')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.IntegerField(db_column='id_pais', primary_key=True, serialize=False)),
                ('id2l', models.CharField(db_column='id2L_Pais', max_length=2)),
                ('id3l', models.CharField(db_column='id3L_Pais', max_length=3)),
                ('nombre', models.CharField(db_column='nombre_pais', max_length=50)),
                ('coord_1_cap', models.FloatField(db_column='coordenada1_pais')),
                ('coord_2_cap', models.FloatField(db_column='coordenada2_pais')),
                ('cod_telefonico', models.IntegerField(db_column='codTelefonico_pais')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PartidoPBA',
            fields=[
                ('id', models.CharField(db_column='id_partido', max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_partido', max_length=50)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'db_table': 'partidopba',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TelefonoEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_column='telefono_escuela', max_length=50)),
                ('cue', models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.escuela')),
            ],
            options={
                'verbose_name': 'Telefono de la Escuela',
                'verbose_name_plural': 'Telefonos de las Escuelas',
                'db_table': 'telefonoescuela',
                'ordering': ['cue'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.IntegerField(db_column='id_provincia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_provincia', max_length=50)),
                ('pais', models.ForeignKey(db_column='pais_provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('apellido_1_persona', models.CharField(max_length=50)),
                ('apellido_2_persona', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_1_persona', models.CharField(max_length=50)),
                ('nombre_2_persona', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento_persona', models.DateField()),
                ('cue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.escuela')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.localidad')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.pais')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['apellido_1_persona'],
            },
        ),
        migrations.CreateModel(
            name='MailEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(db_column='mail_escuela', max_length=254)),
                ('cue', models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.escuela')),
            ],
            options={
                'verbose_name': 'Correo Electronico de la Escuela',
                'verbose_name_plural': 'Correos Electronicos de las Escuelas',
                'db_table': 'mailescuela',
                'ordering': ['cue'],
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='partido',
            field=models.ForeignKey(blank=True, db_column='PartidoPBA_localidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.partidopba'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(db_column='provincia_localidad', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.provincia'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='localidad',
            field=models.ForeignKey(db_column='localidad_escuela', on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.localidad'),
        ),
    ]
