# Generated by Django 4.2 on 2023-05-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escuela',
            options={'ordering': ['cue'], 'verbose_name': 'Escuela', 'verbose_name_plural': 'Escuelas'},
        ),
        migrations.AlterField(
            model_name='mailescuela',
            name='cue',
            field=models.ForeignKey(db_column='id_escuela', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='inscripcion.escuela'),
        ),
    ]
